version: '3'

networks:
    learn_more_nestjs:

services:
    postgresql:
        image: postgres:14.2
        ports:
            - 5455:5432
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        networks:
            - learn_more_nestjs
        volumes:
            - ./volumes/postgresql:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4:latest
        ports:
            - 3500:80
        environment:
            - 'PGADMIN_DEFAULT_EMAIL=root@learn.fr'
            - 'PGADMIN_DEFAULT_PASSWORD=root'
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json
        networks:
            - learn_more_nestjs
